### ISSUE TITLE
Not_working

### ISSUE THREAD

**Issue by JazzyPascal** [mikel-brostrom/yolo_tracking#1036] opened 2023-07-31 10:20 UTC
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

ModuleNotFoundError: No module named 'boxmot.motion.kalman_filters'

I get this error when i try run inference on Google colab

### Environment

Google colab

### Minimal Reproducible Example

!python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source out.avi --save --conf 0.2

**Comment by mikel-brostrom** [comment] 2023-07-31 10:30
Sorry, cannot reproduce. What `boxmot` version do you have installed?

**Comment by JazzyPascal** [comment] 2023-07-31 11:23
Version: 10.0.17

**Comment by mikel-brostrom** [comment] 2023-07-31 11:28
I see what the problem is

**Comment by mikel-brostrom** [comment] 2023-07-31 11:32
I am pushing a new version of the package with the fix to pypi

**Comment by mikel-brostrom** [comment] 2023-07-31 11:37
try pip install `boxmot==10.0.18`

**Comment by JazzyPascal** [comment] 2023-07-31 11:54
ModuleNotFoundError: No module named 'boxmot.postprocessing'

**Comment by mikel-brostrom** [comment] 2023-07-31 12:03
Added a hotfix. pip install boxmot==10.0.19

**Comment by JazzyPascal** [comment] 2023-07-31 12:35
ModuleNotFoundError: No module named 'boxmot.appearance.backbones.clip'

Maybe there's something I'm doing wrong, but I'm running the google colab notebook from the repository...

**Comment by mikel-brostrom** [comment] 2023-07-31 13:11
There is a last `__init__.py` missing

**Comment by mikel-brostrom** [comment] 2023-07-31 13:22
Try `pip install boxmot==10.0.20`. Hopefully everything is fixed now :smile:

**Comment by mikel-brostrom** [comment] 2023-07-31 15:48
Everything should be working now. Let me know if you encounter any issues  :smile:

**Comment by JazzyPascal** [comment] 2023-08-01 07:23
Traceback (most recent call last):
  File "/content/yolo_tracking/examples/track.py", line 9, in <module>
    from boxmot.tracker_zoo import create_tracker
  File "/usr/local/lib/python3.10/dist-packages/boxmot/__init__.py", line 5, in <module>
    from boxmot.trackers.botsort.bot_sort import BoTSORT
  File "/usr/local/lib/python3.10/dist-packages/boxmot/trackers/botsort/bot_sort.py", line 6, in <module>
    from boxmot.appearance.reid_multibackend import ReIDDetectMultiBackend
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/reid_multibackend.py", line 11, in <module>
    from boxmot.appearance.backbones import build_model
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/__init__.py", line 3, in <module>
    from boxmot.appearance.backbones.clip.make_model import make_model
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/clip/make_model.py", line 6, in <module>
    _tokenizer = _Tokenizer()
  File "/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/clip/clip/simple_tokenizer.py", line 66, in __init__
    merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
  File "/usr/lib/python3.10/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/clip/clip/bpe_simple_vocab_16e6.txt.gz'

T_T

**Comment by mikel-brostrom** [comment] 2023-08-01 07:29
I cannot see why this file `/usr/local/lib/python3.10/dist-packages/boxmot/appearance/backbones/clip/clip/bpe_simple_vocab_16e6.txt.gz` isn't uploaded to pypi... I am not ignoring it in `.gitignore`

**Comment by JazzyPascal** [comment] 2023-08-01 08:09
For clarity: I should be installing boxmot==10.0.20 right?

**Comment by mikel-brostrom** [comment] 2023-08-01 08:15
Apparently setup has a default setup by which static files that you want to include in the pkg have to be stated explicitly. I created a `MANIFEST.in` to solve this. I also inspected the newly installed pacakge, the missing file is now included.

**Comment by mikel-brostrom** [comment] 2023-08-01 08:16
Use `boxmot==10.0.23` @JazzyPascal

**Comment by mikel-brostrom** [comment] 2023-08-01 08:31
Finally!!! Thank you for your patience and feedback @JazzyPascal. Enjoy. You will be one of the first ever trying out tracking with CLIP-ReiD :smile:

**Closed** 2023-08-01 08:35 UTC
Labels: bug
