### ISSUE TITLE
Index Error in "boxmot/utils/association.py"

### ISSUE THREAD

**Issue by rachelphilipose** [mikel-brostrom/yolo_tracking#1008] opened 2023-07-19 22:09 UTC
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Hi guys, when I try to run track.py with the following command: 
`
python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source out2.avi --save --conf 0.2 --save-txt --classes 0
`
I get an index error in one of the files. Please note that this has been happening consistently even when I change the arguments in the command. Further, the inferencing appears to work fine, until it hits a frame where this error occurs, so the output videos are abruptly cut off. I have also tried to run multiple different videos, and all had this error, so I'm not sure if I've done something wrong or maybe this is a larger bug? I haven't had any luck lookigng online, but has anyone else experienced this?
`
Traceback (most recent call last):
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/examples/track.py", line 282, in <module>
    main(opt)
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/examples/track.py", line 277, in main
    run(vars(opt))
  File "/home/ubuntu/.virtualenvs/yolo_tracking3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/examples/track.py", line 140, in run
    predictor.tracker_outputs[i] = predictor.trackers[i].update(dets.cpu().detach().numpy(), im0)
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/boxmot/utils/__init__.py", line 55, in wrapper
    mc_dets = self.update(instance, dets, im)
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/boxmot/trackers/deepocsort/deep_ocsort.py", line 443, in update
    matched, unmatched_dets, unmatched_trks = associate(
  File "/home/ubuntu/crowd_analysis/yolo_tracking_new/yolo_tracking/boxmot/utils/association.py", line 355, in associate
    if d not in matched_indices[:, 0]:
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`

### Environment

Yolo Tracking v10.0.16
Python 3.10.6

FULL PIP FREEZE BELOW
absl-py==1.4.0
beautifulsoup4==4.12.2
-e git+https://github.com/mikel-brostrom/yolo_tracking.git@c79e8d5ac113c06ef8bd12724db539b5b871c7b3#egg=boxmot
cachetools==5.3.1
certifi==2023.5.7
cfgv==3.3.1
charset-normalizer==3.2.0
cmake==3.27.0
contourpy==1.1.0
cycler==0.11.0
Cython==3.0.0
distlib==0.3.7
filelock==3.12.2
filterpy==1.4.5
fonttools==4.41.0
gdown==4.7.1
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
identify==2.5.25
idna==3.4
Jinja2==3.1.2
kiwisolver==1.4.4
lapx==0.5.3
lit==16.0.6
loguru==0.7.0
Markdown==3.4.3
MarkupSafe==2.1.3
matplotlib==3.7.2
mpmath==1.3.0
networkx==3.1
nodeenv==1.8.0
numpy==1.23.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
opencv-python==4.8.0.74
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
platformdirs==3.9.1
pre-commit==3.3.3
protobuf==4.23.4
psutil==5.9.5
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyparsing==3.0.9
PySocks==1.7.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scipy==1.11.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
soupsieve==2.4.1
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.0
triton==2.0.0
typing-extensions==4.7.1
tzdata==2023.3
ultralytics==8.0.124
urllib3==1.26.16
virtualenv==20.24.0
Werkzeug==2.3.6

### Minimal Reproducible Example

python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source out2.avi --save --conf 0.2 --save-txt --classes 0

**Comment by mikel-brostrom** [comment] 2023-07-20 06:26
Sorry, cannot reproduce. I just run:

```python examples/track.py --yolo-model yolov8n.pt --reid-model osnet_x0_25_msmt17.pt --source ~/Downloads/test.avi --save --conf 0.2 --save-txt --classes 0```

with no errors

**Comment by rachelphilipose** [comment] 2023-07-20 14:21
I do have the latest in master, I pulled the code using the git pull instructions in the ReadME yesterday. Could you try running it with this specific video? I find it fails at a specific frame each time.

https://github.com/mikel-brostrom/yolo_tracking/assets/121074414/5e5e748f-8c23-4c19-99be-a29561ba2931

**Comment by Jbod23** [comment] 2023-07-24 19:01
same issue here, both on a fresh install of ubuntu 22.04 and clean install of repository, as well as on my mac. Added  some lines to debug/fix the issue in association.py and it works alright now. Not sure if I'm hindering any functionality by my temporary fix, but all seems to work ok. This is what I added at line 354.

`    if len(matched_indices.shape) == 2: # Check that matched_indices is 2D
        for d, det in enumerate(detections):
            if d not in matched_indices[:, 0]:
                unmatched_detections.append(d)
    else:
        unmatched_detections = list(range(len(detections)))

    unmatched_trackers = []
    if len(matched_indices.shape) == 2: # Check that matched_indices is 2D
        for t, trk in enumerate(trackers):
            if t not in matched_indices[:, 1]:
             unmatched_trackers.append(t)
    else:
        unmatched_trackers = list(range(len(trackers)))`

**Comment by mikel-brostrom** [comment] 2023-07-24 20:28
Seems like the multi-class decorator is causing this...

**Comment by mikel-brostrom** [comment] 2023-07-24 20:33
I think I found the issue. here:

```
def linear_assignment(cost_matrix):
    try:
        import lap

        _, x, y = lap.lapjv(cost_matrix, extend_cost=True)
        return np.array([[y[i], i] for i in x if i >= 0])  #
    except ImportError:
        from scipy.optimize import linear_sum_assignment

        x, y = linear_sum_assignment(cost_matrix)
        return np.array(list(zip(x, y)))
```

Could you try installing lap? `pip install lap` an run again?

**Comment by mikel-brostrom** [comment] 2023-07-25 18:02
Could reproduce this. But have to investigate deeper

**Comment by mikel-brostrom** [comment] 2023-07-26 10:12
Ihave a fix for this. Seems like lapx's linear assignment sometimes fails, returning `(0, )` which is incompatible with the indexing here: `matched_indices[:, 0]`. Would you mind double checking this @Jbod23 & @rachelphilipose ?

**Comment by Jbod23** [comment] 2023-07-27 12:09
looks good 👍
Fixed on my end. Thanks!

**Comment by mikel-brostrom** [comment] 2023-07-27 12:13
Thx for checking @Jbod23!

**Closed by mikel-brostrom** 2023-07-27 12:13 UTC
Labels: bug
