### ISSUE TITLE
ocsort_kf breaks with update to dques

### ISSUE THREAD

**Issue by johannesgeibel** [mikel-brostrom/yolo_tracking#1366] opened 2024-03-20 19:04 UTC
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Hi,
after the update to deques (10.0.59) OCSORT breaks in `KalmanFilter.unfreeze()` . First, a deque cannot be slized, breaking this line:
```
self.history_obs = self.history_obs[:-1]
```
replacing by `_ = self.history_obs.pop()` seemed to resolve the issue, but in later frames following error occured:
```
File "/data/users/johannes.geibel/miniconda3/envs/yolo/lib/python3.11/site-packages/boxmot/motion/kalman_filters/ocsort_kf.py", line 400, in unfreeze
    index1 = indices[-2]
             ~~~~~~~^^^^
IndexError: index -2 is out of bounds for axis 0 with size 1
```
And I am not really sure where the problem comes from then...

Reverting boxmot to 10.0.57 resolved all issues

Regards,
Johannes

### Environment

boxmot v. 10.0.59

### Minimal Reproducible Example

...

**Comment by mikel-brostrom** [comment] 2024-03-20 19:49
https://github.com/mikel-brostrom/yolo_tracking/pull/1367

**Comment by mikel-brostrom** [comment] 2024-03-20 20:02
Should be fixed. Let me know 😄

**Comment by arashrocky** [comment] 2024-03-20 22:34
Hi @mikel-brostrom.
I have faced the same issue. After cloning your newer Release v10.0.60 another problem is emerged, as follows:

File "/home/arash/TAD/ObjectTrack/Yolov8_mikel-brostrom/yolo_tracking/boxmot/motion/kalman_filters/deepocsort_kf.py", line 506, in update
    self.history_obs.append(z)
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by yflin1** [comment] 2024-03-21 02:46
> Hi @mikel-brostrom. I have faced the same issue. After cloning your newer Release v10.0.60 another problem has emerged, as follows:
> 
> File "/home/arash/TAD/ObjectTrack/Yolov8_mikel-brostrom/yolo_tracking/boxmot/motion/kalman_filters/deepocsort_kf.py", line 506, in update self.history_obs.append(z) AttributeError: 'NoneType' object has no attribute 'append'

Me too.

**Comment by mikel-brostrom** [comment] 2024-03-21 08:17
Oh, I missed to replace the last indexing in DeepOCSORT

**Comment by mikel-brostrom** [comment] 2024-03-21 08:35
Try again please 😄

**Comment by yflin1** [comment] 2024-03-22 08:09
> Try again please 😄

Great! The problem is solved. Thank you very much!

**Comment by mikel-brostrom** [comment] 2024-03-22 10:58
This:

> File "/data/users/johannes.geibel/miniconda3/envs/yolo/lib/python3.11/site-packages/boxmot/motion/kalman_filters/ocsort_kf.py", line 400, in unfreeze
>     index1 = indices[-2]
>              ~~~~~~~^^^^
> IndexError: index -2 is out of bounds for axis 0 with size 1

Should be now fixed as well @johannesgeibel

**Comment by arashrocky** [comment] 2024-03-22 21:41
> Try again please 😄

Thanks mikel. It works fine, but I recommend those who face similar issue to remove the environment and redefine all packages and dependencies again in new environment. This will avoid confusions.

**Comment by mikel-brostrom** [comment] 2024-03-26 20:59
Your are right. The `max_age` cannot be longer than the history

**Comment by mikel-brostrom** [comment] 2024-03-26 21:02
> Could this be due to the dques being fixed at length 50, and I do not have observations over a longer time period (while max_age being set to 50 as well?

Aha, that is why I couldn't find this bug 🤣. In the repo `max_age` is set to 30. I think an assertion here would be enough

**Comment by ch3ny1** [comment] 2024-04-01 19:58
The same bug
`File "/media/chenyi/Elements/Tools/yolo_tracking-master/boxmot/motion/kalman_filters/hybridsort_kf.py", line 399, in unfreeze
    index1 = indices[-2]
IndexError: index -2 is out of bounds for axis 0 with size 1
`
 is happening to HybridSORT, though the line seems to have been updated according to previous comments `self.history_obs = deque(list(self.history_obs)[:-1])`.

Any idea on how to solve this bug?

**Comment by mikel-brostrom** [comment] 2024-04-08 07:45
This was updated in the last release @ch3ny1. Check out master

**Closed by mikel-brostrom** 2024-04-08 07:45 UTC
Labels: bug

**Comment by TSLNIHAOGIT** [comment] 2024-04-09 05:39
> This was updated in the last release @ch3ny1. Check out master
The bug is still there,when  i run the last release code!

ile "/mnt/e/python_project_new/yolo_tracking-10.0.65/boxmot/utils/__init__.py", line 79, in wrapper
    tracks = self.update(instance, dets, im)
  File "/mnt/e/python_project_new/yolo_tracking-10.0.65/boxmot/trackers/hybridsort/hybridsort.py", line 469, in update
    self.active_tracks[m[1]].update(dets[m[0], :], dets0[m[0], 5], dets0[m[0], 6], id_feature_keep[m[0], :])
  File "/mnt/e/python_project_new/yolo_tracking-10.0.65/boxmot/trackers/hybridsort/hybridsort.py", line 286, in update
    self.kf.update(convert_bbox_to_z(bbox))
  File "/mnt/e/python_project_new/yolo_tracking-10.0.65/boxmot/motion/kalman_filters/hybridsort_kf.py", line 487, in update
    self.unfreeze()
  File "/mnt/e/python_project_new/yolo_tracking-10.0.65/boxmot/motion/kalman_filters/hybridsort_kf.py", line 399, in unfreeze
    index1 = indices[-2]
IndexError: index -2 is out of bounds for axis 0 with size 1

**Comment by mikel-brostrom** [comment] 2024-04-12 09:09
What have you set `max_age` to? @TSLNIHAOGIT

**Comment by liamwebsterxyz** [comment] 2024-04-26 06:05
I have tried max_age == 10, 20 and 30 and the same traceback

**Comment by chensonglu** [comment] 2024-04-27 06:04
> The same bug `File "/media/chenyi/Elements/Tools/yolo_tracking-master/boxmot/motion/kalman_filters/hybridsort_kf.py", line 399, in unfreeze index1 = indices[-2] IndexError: index -2 is out of bounds for axis 0 with size 1 ` is happening to HybridSORT, though the line seems to have been updated according to previous comments `self.history_obs = deque(list(self.history_obs)[:-1])`.
> 
> Any idea on how to solve this bug?

same problem

**Comment by DenisN03** [comment] 2024-06-03 08:32
I faced the same problem. Is there a solution?
